# Generated by Django 5.2.6 on 2025-09-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('institution', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ecole', models.CharField(blank=True, max_length=150, null=True)),
                ('specialite', models.CharField(blank=True, max_length=150, null=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('lieu_affectation', models.CharField(blank=True, max_length=150, null=True, verbose_name="Lieu d'Affectation")),
                ('type_stage', models.CharField(choices=[('Academique', 'Académique'), ('Professionnel', 'Professionnel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Validé', 'Validé')], default='En cours', max_length=20)),
                ('encadrant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.encadrant')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Archivé', 'Archivé')], default='En attente', max_length=20)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('derniere_modif', models.DateTimeField(auto_now=True)),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='stages.stage')),
            ],
        ),
    ]
