# Generated by Django 5.2.6 on 2025-09-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_fichier', models.FileField(upload_to='rapports/')),
                ('etat_archivage', models.CharField(choices=[('Archivé', 'Archivé'), ('Non archivé', 'Non archivé')], default='Non archivé', max_length=20)),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stages.stage')),
            ],
        ),
    ]
