# Generated by Django 5.2.6 on 2025-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadrant',
            name='nom_institution',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'institution"),
        ),
    ]
