# Generated by Django 5.2.6 on 2025-09-17 10:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_rapport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='chemin_fichier',
            new_name='fichier',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='date_soumission',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='etat_archivage',
        ),
        migrations.AddField(
            model_name='rapport',
            name='date_depot',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rapport',
            name='derniere_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Archivé', 'Archivé')], default='En attente', max_length=20),
        ),
        migrations.AddField(
            model_name='rapport',
            name='titre',
            field=models.CharField(default='Rapport de stage', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='stages.stage'),
        ),
    ]
