# Generated by Django 5.2.6 on 2025-10-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_encadrant_nom_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='decision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de décision'),
        ),
        migrations.AddField(
            model_name='stage',
            name='lettre_acceptation',
            field=models.FileField(blank=True, null=True, upload_to='lettres_acceptation/', verbose_name="Lettre d'acceptation scannée"),
        ),
    ]
