# Generated by Django 5.2.6 on 2025-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_rename_chemin_fichier_rapport_fichier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='titre',
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date_depot',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
