# Generated by Django 5.2.6 on 2025-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_stage_decision_stage_lettre_acceptation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='lieu_affectation',
        ),
        migrations.AddField(
            model_name='stage',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Service d'affectation"),
        ),
        migrations.AddField(
            model_name='stage',
            name='service_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='unite',
            field=models.CharField(default=" ", max_length=100, verbose_name="Unité d'affectation"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='unite_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
