# Generated by Django 5.2.6 on 2025-10-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_remove_stage_lieu_affectation_stage_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='stage',
            name='direction_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='stage',
            name='division_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
