# Generated by Django 5.2.6 on 2025-10-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_stage_direction_stage_direction_nom_stage_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='unite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Unité d'affectation"),
        ),
    ]
