# Generated by Django 5.2.6 on 2025-10-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_alter_stage_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='direction_nom',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='division_nom',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='service_nom',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='unite_nom',
        ),
    ]
